title: AI Agent Benchmarking Framework
description: Standardized evaluation framework for business AI agents
baseurl: "/ai-agent-benchmark"
url: "https://ninajlu.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
show_downloads: true
theme: jekyll-theme-cayman

github:
  is_project_page: true
  repository_url: "https://github.com/ninajlu/ai-agent-benchmark"

# Custom settings
github_username: ninajlu
twitter_username: ninajlu 