title: AI Agent Benchmarking Framework
description: Standardized evaluation framework for business AI agents
baseurl: "/ai-agent-benchmark"
url: "https://ninajlu.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom settings
github_username: ninajlu
twitter_username: ninajlu 